### ISSUE TITLE
module 'robustocs' has no attribute 'solverROCS'

### ISSUE THREAD

**Issue by sakurita17** [Foggalong/RobustOCS#31]
When I try to use solveROCS, I get the error: module 'robustocs' has no attribute 'solveROCS'. What could be the issue? :)

Thanks, Jaime

**Comment by Foggalong** [comment]
@sakurita17 After doing `git pull` for #29, is this also fixed?

**Comment by Foggalong** [comment]
Never mind, I managed to replicate this! The new utility functions were missing off the default import list. Added them to the git version and will tag a 0.2.2 release along with any other bug fixes accumulated over the next couple days. 

If you need to use it in the meantime, it can still be accessed in 0.2.1 using `robustocs.utils.solverROCS`. For example

```bash python3
>>> import robustocs
>>> robustocs.__version__
'0.2.1'
>>> robustocs.utils.solveROCS
<function solveROCS at 0x7f5f04dbcf70>
```
